// gb-music-manage/src/views/register/Register.vue
<template>
  <div class="register">
    <div class="reg-outer">
      <Login :is-show="false" @login="register">
        <button slot="btn">注册</button>
      </Login>
    </div>
  </div>
</template>

<script>
import Login from '../../components/common/login/Login';
import { register } from '../../network/login';

export default {
  name: 'Register',
  components: {
    Login
  },
  methods: {
    register(userName, password) {
      console.log(userName, password);
      register(userName, password).then((data) => {
        if (data) {
          this.$router.push({
            path: '/Login'
          });
        }
      });
    }
  }
};
</script>

<style scoped lang="less">
.register {
  position: relative;
  height: 700px;
  .reg-outer {
    box-shadow: 0 0 25px rgba(0, 0, 0, 0.15);
    background-color: #fff;
    position: absolute;
    left: 50%;
    top: 10%;
    padding: 30px;
    border-radius: 10px;
    transform: translate(-50%, 0);
  }
}
</style>

// gb-music-client/src/views/register/index.tsx
import React, { memo } from 'react';
import { RouteComponentProps } from 'react-router-dom';
import LoginCpn from '../../components/content/loginCpn';
import { RegisterWrapper } from './style';
import { register } from '../../network/login';
import Bgc from './childCpn/bgc';
const Register: React.FC<RouteComponentProps> = (props) => {
  const registerHandle = (userName: string, password: string) => {
    register(userName, password).then((data) => {
      if (data) {
        props.history.push({
          pathname: '/Login'
        });
      }
    });
  };
  return (
    <RegisterWrapper>
      <Bgc />
      <div className="register">
        <LoginCpn
          isShow={false}
          onClick={(userName: string, password: string) => registerHandle(userName, password)}
          btn={<button className="reg-btn">注册</button>}
        />
      </div>
    </RegisterWrapper>
  );
};
export default memo(Register);
