// gb-music-vue/src/components/content/detail/toplistDetail/ToplistDetail.vue
<template>
  <div class="toplist-outer">
    <div class="head">
      <div class="img-container">
        <img :src="toplist.coverUrl" :alt="toplist.name" />
      </div>
      <div class="msg">
        <div class="title">{{ toplist.name }}</div>
        <div class="user">
          <UserMsg
            item-width="20px"
            :user-name="toplist.user.userName"
            :avatar-url="toplist.user.avatarUrl"
          />
          <div class="create-time" v-if="toplist.createTime">
            {{ (toplist.createTime, 'yyyy-MM-dd' | timeFormat) }}
          </div>
        </div>
        <div class="play-count">播放量: {{ toplist.playCount }}</div>
        <div class="count">歌曲数:{{ toplist.songs.length }}</div>
      </div>
    </div>
    <div class="content-body">
      <TabControl :list="['歌曲']">
        <template v-slot:0>
          <SongList :songs="toplist.songs" :tId="toplist.id" v-if="toplist.songs.length" />
        </template>
      </TabControl>
    </div>
  </div>
</template>

<script>
import { getToplistDetail } from '@/network/toplist';
import UserMsg from '@/components/common/userMsg/UserMsg';
import format from '@/utils/filter';
import TabControl from '@/components/common/tabControl/TabControl';
import SongList from './childCpn/songList/SongList';
export default {
  name: 'ToplistDetail',
  components: { SongList, TabControl, UserMsg },
  data() {
    return {
      id: '',
      toplist: {
        user: {},
        songs: []
      }
    };
  },
  filters: format,
  created() {
    this.id = this.$route.query.id;
    getToplistDetail(this.id).then((data) => {
      this.toplist = data;
    });
  }
};
</script>

<style scoped lang="less">
.toplist-outer {
  background-color: #fff;
  padding: 20px;
}
.head {
  display: flex;
  .img-container {
    width: 150px;
    overflow: hidden;
    img {
      border-radius: 5px;
      width: 100%;
    }
  }
  .msg {
    margin: 0 0 0 20px;
    .title {
      font-size: 20px;
      font-weight: bold;
    }
    .user {
      display: flex;
      align-items: center;
      margin: 10px 0 0 0;
      .create-time {
        margin: 0 0 0 10px;
      }
    }
    .play-count {
      margin: 15px 0;
    }
  }
}
</style>

// gb-music-client-new/src/components/content/detail/toplistDetail/index.tsx
import React, { memo, FC, ReactElement, useEffect, useState } from 'react';
import { useNavigate,useLocation } from 'react-router-dom';
import { CenterContentWrapper, ToplistDetailWrapper, RightContent, LeftContent } from './style';
import { getToplistDetail } from '../../../../network/toplist/toplist';
import { IToplist } from '../../../../constant/toplist';
import { ISong } from '../../../../constant/song';
import UserMsg from '../../../common/userMsg';
import { formatTime } from '../../../../utils/format';
import TabControl from '../../../common/tabControl';
import SongList from '../playlistDetail/childCpn/songList';
import Comment from './childCpn/comment';
import SimiToplist from './childCpn/simiToplist';

interface IDetail extends IToplist {
  songs: ISong[];
}
const ToplistDetail: FC<{ id: string; name: string; userId: string }> = (
  props
): ReactElement => {
  const location = useLocation();
  const navigate = useNavigate();
  const { id, name } = location.state;
  const [detail, setDetail] = useState<IDetail>();
  const [tid, setTId] = useState<string>(id);
  const [tName,setTname]=useState<string>(name);
  useEffect(() => {
    getToplistDetail(tid).then((data: any) => {
      setDetail(data);
    });
  }, [tid]);
  const userRouter = (id: string) => {
    navigate('/Home/userDetail',{
      state: {
        userId: id,
        id: '',
        name: ''
      }
    });
  };
  const toplistClick = (id: string,name:string) => {
    setTId(id);
    setTname(name)
  };
  return (
    <ToplistDetailWrapper>
      <CenterContentWrapper>
        {detail && (
          <LeftContent>
            <div className="toplist-detail-header">
              <div className="img-container">
                <img src={detail.coverUrl} alt="" />
              </div>
              <div className="msg">
                <div className="toplist-name">{detail.name}</div>
                <div className="user-time">
                  <UserMsg
                    avatarUrl={detail.user!.avatarUrl}
                    userName={detail.user!.userName}
                    userId={detail.user!.userId}
                    imgWidth="25px"
                    onClick={(id: string) => userRouter(id)}
                  />
                  <div className="time">
                    <span>创建于:</span>
                    <span>{formatTime(detail.createTime!, 'yyyy-MM-dd')}</span>
                  </div>
                </div>
                <div className="count">
                  <div className="song-count">
                    <span>歌曲:</span>
                    <span>{detail.songs.length}</span>
                  </div>
                  <div className="play-count">
                    <span>播放量:</span>
                    <span>{detail.playCount}</span>
                  </div>
                </div>
                <div className="desc">
                  <span>简介:</span>
                  {detail.description}
                </div>
              </div>
            </div>
            <div className="body-content">
              {detail.songs && (
                <TabControl
                  list={['歌曲列表', '评论']}
                  contentName={['songList', 'comment', 'sub']}
                  songList={<SongList songs={detail.songs} isShowUp={tName === '飙升榜'} tId={tid} />}
                  comment={<Comment id={detail.id} />}
                />
              )}
            </div>
          </LeftContent>
        )}
        <RightContent>
          <SimiToplist id={tid} onClick={(id,name) => toplistClick(id,name)} />
        </RightContent>
      </CenterContentWrapper>
    </ToplistDetailWrapper>
  );
};
export default memo(ToplistDetail);
